### PR TITLE
CD: Remove use of env var

### PR DESCRIPTION
**Pull request by tskarhed**
Uses the --location cli option at build instead.

### CODE REVIEW

**Comment by MrTengil** [comment]
We can use env variables if we want to: https://docs.deno.com/runtime/manual/basics/env_variables
Then we can just setup a local .env file and have it work.
Whatya think?

**Comment by tskarhed** [comment]
No real reason when you can use the --location 🤷 We might need it in the future for other reasons.

**Comment by MrTengil** [comment]
> No real reason when you can use the --location 🤷 We might need it in the future for other reasons.

Ok looks good then 👍

**Comment by tskarhed** [comment]
> > No real reason when you can use the --location 🤷 We might need it in the future for other reasons.
> 
> Ok looks good then 👍

Ok, thanks for coming to my TED talk

**Review by MrTengil — APPROVED** [review]
LGTM!

**Pull request merged**
